name: 'Build and Release'

on:
  push:
    tags:
      - 'v*'  # 只匹配以 'v' 开头的标签，如 v1.0.0

jobs:
  build-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'  # 替代手动 git submodule update
      
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/Hydrogen'
          cache: 'npm'
          cache-dependency-path: 'ui/package-lock.json'
      
      - name: Install UI dependencies
        working-directory: ./ui
        run: npm ci  # 更严格的依赖安装，适合 CI 环境
      
      - name: Build UI
        working-directory: ./ui
        run: npm run build
      
      - uses: actions/upload-artifact@v3
        with:
          name: ui-dist
          path: ui/dist

  build-binary:
    needs: build-ui
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - { goos: linux, goarch: amd64 }
          - { goos: linux, goarch: arm64 }
          - { goos: darwin, goarch: amd64 }
          - { goos: darwin, goarch: arm64 }
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'backend/go.mod'
          cache: true
          cache-dependency-path: 'backend/go.sum'
      
      - uses: actions/download-artifact@v3
        with:
          name: ui-dist
          path: backend/embed/ui
      
      - name: Build Binary
        working-directory: ./backend
        run: |
          GOOS=${{ matrix.target.goos }} GOARCH=${{ matrix.target.goarch }} \
          go build -v -ldflags="-s -w" -o als-${{ matrix.target.goos }}-${{ matrix.target.goarch }}
      
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            backend/als-${{ matrix.target.goos }}-${{ matrix.target.goarch }}
          tag_name: ${{ github.ref_name }}
